<a href="https://colab.research.google.com/github/satyaprakashmehta/ai-ml-practice/blob/master/25_aug_first_data_processing_steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Template

## Importing the libraries

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [43]:
dataset = pd.read_csv("https://raw.githubusercontent.com/satyaprakashmehta/ai-ml-practice/master/reports.csv")
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values 

print(X)
print(Y)

[['Bihar' 23 'male' 'single' 'veg' 'student' 12.0 2100.0]
 ['Delhi' 32 'female' 'married' 'veg' 'professional' 15.0 1600.0]
 ['Karnataka' 22 'male' 'single' 'veg' 'student' 18.0 1450.0]
 ['Punjab' 29 'female' nan 'nonveg' 'professional' 17.0 1660.0]
 ['Bihar' 25 'male' 'single' 'veg' 'professional' 35.0 1290.0]
 ['Punjab' 32 'male' 'married' 'nonveg' 'professional' nan 1360.0]
 ['Karnataka' 23 'female' nan 'nonveg' 'student' nan 1200.0]
 ['Bihar' 25 'female' 'married' nan 'professional' 12.0 2500.0]
 ['Punjab' 26 'male' 'single' 'veg' 'student' 21.0 2210.0]
 ['Bihar' 28 'male' 'married' nan 'professional' 12.0 2200.0]
 ['Delhi' 31 'male' 'married' 'nonveg' 'professional' nan 1530.0]
 ['Karnataka' 21 'female' 'single' 'nonveg' 'student' 11.0 nan]
 ['Punjab' 25 'male' 'single' 'veg' 'student' nan 2000.0]
 ['Delhi' 28 'female' 'single' 'veg' 'professional' 15.0 1580.0]
 ['Delhi' 32 'male' 'married' 'veg' 'professional' 17.0 1360.0]
 ['Bihar' 21 'female' 'married' 'nonveg' 'student' 1.0 na

# **Taking Care of Missing Data**

In [44]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent') 

imputer.fit(X)
X=imputer.transform(X)
print(X)	


#imputer.fit(Y)
#Y=imputer.transform(Y)
#print(Y)

[['Bihar' 23 'male' 'single' 'veg' 'student' 12.0 2100.0]
 ['Delhi' 32 'female' 'married' 'veg' 'professional' 15.0 1600.0]
 ['Karnataka' 22 'male' 'single' 'veg' 'student' 18.0 1450.0]
 ['Punjab' 29 'female' 'married' 'nonveg' 'professional' 17.0 1660.0]
 ['Bihar' 25 'male' 'single' 'veg' 'professional' 35.0 1290.0]
 ['Punjab' 32 'male' 'married' 'nonveg' 'professional' 12.0 1360.0]
 ['Karnataka' 23 'female' 'married' 'nonveg' 'student' 12.0 1200.0]
 ['Bihar' 25 'female' 'married' 'veg' 'professional' 12.0 2500.0]
 ['Punjab' 26 'male' 'single' 'veg' 'student' 21.0 2210.0]
 ['Bihar' 28 'male' 'married' 'veg' 'professional' 12.0 2200.0]
 ['Delhi' 31 'male' 'married' 'nonveg' 'professional' 12.0 1530.0]
 ['Karnataka' 21 'female' 'single' 'nonveg' 'student' 11.0 1360.0]
 ['Punjab' 25 'male' 'single' 'veg' 'student' 12.0 2000.0]
 ['Delhi' 28 'female' 'single' 'veg' 'professional' 15.0 1580.0]
 ['Delhi' 32 'male' 'married' 'veg' 'professional' 17.0 1360.0]
 ['Bihar' 21 'female' 'married' 'n

# Encoading the independent 


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0,2,3,4,5])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

print(X)

[[1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 23 12.0 2100.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 32 15.0 1600.0]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 22 18.0 1450.0]
 [0.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 29 17.0 1660.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 1.0 0.0 25 35.0 1290.0]
 [0.0 0.0 0.0 1.0 0.0 1.0 1.0 0.0 1.0 0.0 1.0 0.0 32 12.0 1360.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 23 12.0 1200.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 25 12.0 2500.0]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 26 21.0 2210.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 1.0 0.0 28 12.0 2200.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 1.0 0.0 1.0 0.0 31 12.0 1530.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 21 11.0 1360.0]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 25 12.0 2000.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 1.0 0.0 28 15.0 1580.0]
 [0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 1.0 0.0 32 17.0 1360.0]
 [1.0 0.0 

# Encoding the dependent variable

In [48]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)

print(Y)

[1 1 0 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 1]
