<a href="https://colab.research.google.com/github/satyaprakashmehta/ai-ml-practice/blob/master/numpy/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPY - Practice

In [1]:
import numpy as np

1-D Array

In [25]:
one_D_Array = np.array([1,2,3,4])

print(one_D_Array)

print(one_D_Array.size)

print(one_D_Array.ndim)

print(one_D_Array.shape)

print(one_D_Array.dtype)

[1 2 3 4]
4
1
(4,)
int64


2-D Array

In [26]:
two_D_Array = np.array(([1,2,3,4],[5,6,7,8]))

print(two_D_Array)

print(two_D_Array.size)

print(two_D_Array.ndim)

print(two_D_Array.shape)

print(two_D_Array.dtype)

[[1 2 3 4]
 [5 6 7 8]]
8
2
(2, 4)
int64


1-D Array dtype

In [29]:
one_D_Array = np.array(['a'], dtype=str)

print(one_D_Array)

print(one_D_Array.size)

print(one_D_Array.ndim)

print(one_D_Array.shape)

print(one_D_Array.dtype)

['a']
1
1
(1,)
<U1


1/2-D 0th and 1s Matrix

In [53]:
zero_matrix = np.ones([5,5])
zero_matrix = np.zeros([5,5])

zero_matrix = np.ones([5,5], dtype=int)
zero_matrix = np.zeros([5,5], dtype=int)

zero_matrix = np.ones([5,5], dtype=bool)
zero_matrix = np.zeros([5,5], dtype=bool)

zero_matrix = np.ones([5,5], dtype=str)
zero_matrix = np.zeros([5,5], dtype=str)


zero_matrix = np.empty([5,5])
zero_matrix = np.empty([5,5])

zero_matrix = np.empty([5,5], dtype=str)
zero_matrix = np.empty([5,5], dtype=str)

print(zero_matrix)
print(zero_matrix.size)
print(zero_matrix.ndim)
print(zero_matrix.shape)
print(zero_matrix.dtype)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
25
2
(5, 5)
<U1
[1 2 3 4 5 6 7 8 9]


In [78]:
one_d_array = np.ones(9, dtype=int)

print(one_d_array.reshape(3,3).reshape(9))




[1 1 1 1 1 1 1 1 1]
